language: python
python:
    - "2.7"
before_install:
  - sudo apt-get install libblas-dev
  - sudo apt-get install liblapack-dev
  - sudo apt-get install gfortran
install:
    - pip install -r requirements.txt
script:
    - py.test
notifications:
    email:
        recipients:
            - matthew.a.hoover@gmail.com
sudo:
  - required
